[package]
name = "meigenbot-rust"
version = "0.1.0"
authors = ["kawaemon <34652535+kawaemon@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.111", features = ["derive"] }
serde_yaml = "0.8.12"

rand = "0.7.3"
log = "0.4.8"
stderrlog = "0.4.3"

mongodb = "1.0.0"
bson = "1.0.0"

tokio = { version = "0.2.21", features = ["full"] }
async-trait = "0.1.36"
readonly = "0.1.6"

[dependencies.serenity]
git = "https://github.com/acdenisSK/serenity"
branch = "await_next"
default-features = false
features = ["rustls_backend", "cache", "client", "gateway", "model"]